config/routes.rb
Shoppe::Engine.routes.draw do
  resources :posts do
    post :search, on: :collection
  end
  resources :post_categories do
  end
  resources :services do
  end
end
Rails.application.routes.draw do

  #
  # Shoppe admin interface
  #
  mount Shoppe::Engine => "/admin"

  #
  # Product browising
  #
  get 'products' => 'products#categories', :as => 'catalogue'
  get 'products/filter' => 'products#filter', :as => 'product_filter'
  get 'products/:category_id' => 'products#index', :as => 'products'
  get 'products/:category_id/:product_id' => 'products#show', :as => 'product'
  post 'products/:category_id/:product_id/buy' => 'products#add_to_basket', :as => 'buy_product'

  #
  # Order status
  #
  get 'order/:token' => 'orders#status', :as => 'order_status'

  #
  # Basket
  #
  get 'basket' => 'orders#show', :as => 'basket'
  delete 'basket' => 'orders#destroy', :as => 'empty_basket'
  post 'basket/:order_item_id' => 'orders#change_item_quantity', :as => 'adjust_basket_item_quantity'
  delete 'basket/:order_item_id' => 'orders#change_item_quantity'
  delete 'basket/delete/:order_item_id' => 'orders#remove_item', :as => 'remove_basket_item'

  #
  # Checkout
  #
  match 'checkout' => 'orders#checkout', :as => 'checkout', :via => [:get, :patch]
  match 'checkout/delivery' => 'orders#change_delivery_service', :as => 'change_delivery_service', :via => [:post]
  match 'checkout/pay' => 'orders#payment', :as => 'checkout_payment', :via => [:get, :patch]
  match 'checkout/confirm' => 'orders#confirmation', :as => 'checkout_confirmation', :via => [:get, :patch]

  #
  # Post browising
  #
  get 'blogs' => 'posts#index', :as => 'posts'
  get 'blogs/filter' => 'posts#filter', :as => 'post_filter'
  # get 'blogs/:category_id' => 'posts#index', :as => 'posts'
  get 'blogs/:category_id/:post_id' => 'posts#show', :as => 'post'
  # post 'posts/:category_id/:post_id/buy' => 'posts#add_to_basket', :as => 'buy_product'

  # Service browsing
  get 'services' => 'services#index', as: 'services'
  get 'services/:service_id' => 'services#show', :as =>'service'
  #
  # Static pages
  #
  get ':action', :controller => 'pages', :as => 'page'

  #
  # Homepage
  #
  root :to => 'pages#home'
end

app/views/shared/_basket.html.haml
.basket
  - if has_order? && current_order.has_items?
    %p.quantity <b>#{pluralize current_order.total_items, 'item'}</b> in your shopping bag
    %p.amount <b>#{number_to_currency current_order.total_before_tax}</b> (ex. tax &amp; delivery)
    %p.buttons
      = link_to "View my bag", basket_path
      = link_to "Checkout", checkout_path, :class => 'checkout'

  - else
    %p.empty <b>Your shopping bag is empty.</b> 
    %p.empty How dare it be?! Why not add some stuff to it?

app/views/shared/_breadcrumb.html.haml
/ breadcrumb start
/ ================
.breadcrumb-container
  .container
    %ol.breadcrumb
      %li
        %i.fa.fa-home.pr-10
        %a{:href => "index.html"} Home
      %li.active Blog Post
      / breadcrumb end

app/views/shared/_choose_us.html.haml
/ section why choose us
/ ================
%section.pv-30
  .container
    .row
      .col-md-8.col-md-offset-2
        %h2.text-center
          Tại sao bạn nên chọn
          %strong Lọ Lem
          Spa
        .separator
        %p.large.text-center
          Vì sao bạn nên lựa chọn chúng tôi ... tạo được uy tín lớn trong lòng quý khách hàng nhiều năm qua, là lí do để bạn nên lựa chọn các dịch vụ làm đẹp tại đây.
        %br
  .container
    .row
      .col-md-6
        = image_tag("lolem_spa_phan_thiet.jpg")
      .col-md-6
        %p.space-top
          #{Shoppe.settings.store_name} đảm bảo với bạn sự phục vụ nhiệt tình nhất, chuyên nghiệp nhất trong một môi trường không gian vừa lịch sự vừa thoải mái nhất. Trách nhiệm của chúng tôi là luôn đổi mới, cập nhật những công nghệ mới nhất. Đối với chúng tôi, khách hàng là thượng đế và để đảm bảo tất cả các yếu tố kể trên tại cơ sở của #{Shoppe.settings.store_name} có các điểm khác biệt như sau:
        .media
          .media-left.pr-20
            %a{:href => "#"}
              %span.icon.circle.small.default-bg
                %i.icon-eye
          .media-body
            %h4.media-heading ĐỘI NGŨ NHÂN VIÊN
            Với đội ngũ nhân viên tay nghề cao, đến với Spa chúng tôi bạn sẽ trải nghiệm những dịch vụ với sự phục vụ tận tình và chu đáo nhất.
        .media
          .media-left.pr-20
            %a{:href => "#"}
              %span.icon.circle.small.default-bg
                %i.icon-trophy
          .media-body
            %h4.media-heading CƠ SỞ VẬT CHẤT
            Cơ sở vật chất hiện đại, thiết kế phòng óc khang trang... Phòng Spa kết hợp Âu – Á vừa sang trọng, hiện đại, vừa ấm áp, vừa thư thái.
        .media
          .media-left.pr-20
            %a{:href => "#"}
              %span.icon.circle.small.default-bg
                %i.icon-lifebuoy
          .media-body
            %h4.media-heading GIÁ CẢ HỢP LÝ
            #{Shoppe.settings.store_name} tự hào là hệ thống tiên phong trong việc đưa đến các dịch vụ làm đẹp tiên tiến nhất, hiện đại nhất theo công nghe Hàn Quốc với mức chi phí vô cùng hợp lý và đa dạng, phù hợp với mọi nhu cầu và tình hình tài chính của khách hàng.
        %p
          %a.btn.btn-default-transparent.btn-animated{:href => "#"}
            Chi tiết
            %i.fa.fa-arrow-right.pl-10
              / section end

app/views/shared/_core_feature.html.haml
/ ================ core features
%section.light-gray-bg.pv-30.clearfix
  .container
    .row
      .col-md-8.col-md-offset-2
        %h2.text-center
          %strong LỌ LEM SPA cam kết
        .separator
        %p.large.text-center
          Hiệu quả thật 100% - Cam Kết không trắng hoàn tiền 100%
      .col-md-3
        .pv-30.ph-20.feature-box.bordered.shadow.text-center.object-non-visible{"data-animation-effect" => "fadeInDownSmall", "data-effect-delay" => "100"}
          %span.icon.default-bg.circle
            %i.fa.fa-diamond
          .separator.clearfix
          %p
            Trắng lên ít nhất 2 đến 4 tone so với da cũ!
      .col-md-3
        .pv-30.ph-20.feature-box.bordered.shadow.text-center.object-non-visible{"data-animation-effect" => "fadeInDownSmall", "data-effect-delay" => "100"}
          %span.icon.default-bg.circle
            %i.fa.fa-diamond
          .separator.clearfix
          %p
            Ko hại da ko mòn da ko bắt nắng!
      .col-md-3
        .pv-30.ph-20.feature-box.bordered.shadow.text-center.object-non-visible{"data-animation-effect" => "fadeInDownSmall", "data-effect-delay" => "100"}
          %span.icon.default-bg.circle
            %i.fa.fa-diamond
          .separator.clearfix
          %p
            Đều màu - không trắng bệch hay loang lố
      .col-md-3
        .pv-30.ph-20.feature-box.bordered.shadow.text-center.object-non-visible{"data-animation-effect" => "fadeInDownSmall", "data-effect-delay" => "100"}
          %span.icon.default-bg.circle
            %i.fa.fa-diamond
          .separator.clearfix
          %p
            Không hồi da đen

app/views/shared/_footer.html.haml
%footer#footer.clearfix
  / .footer start
  / ================
  .footer
    .container
      .footer-inner
        .row
          .col-md-3
            .footer-content
              .logo-footer= image_tag("logo.png")
              %p
                #{Shoppe.settings.short_description}...
                %a{:href => "page-about.html"}
                  Chi tiết
                  %i.fa.fa-long-arrow-right.pl-5
              .separator-2
              %nav
                %ul.nav.nav-pills.nav-stacked
                  %li
                    %a{:href => "#", :target => "_blank"} Hỗ trợ
                  %li
                    %a{:href => "#"} Chính sách
                  %li
                    %a{:href => "#"} Quy định
                  %li
                    %a{:href => "#"} Giới thiệu
          .col-md-3
            .footer-content
              =render 'shared/recent_post'
          .col-md-3
            .footer-content
              %h2.title Portfolio Gallery
              .separator-2
              .row.grid-space-10
                .col-xs-4.col-md-6
                  .overlay-container.mb-10
                    = image_tag("gallery-1.jpg")
                    %a.overlay-link.small{:href => "portfolio-item.html"}
                      %i.fa.fa-link
                .col-xs-4.col-md-6
                  .overlay-container.mb-10
                    = image_tag("gallery-2.jpg")
                    %a.overlay-link.small{:href => "portfolio-item.html"}
                      %i.fa.fa-link
                .col-xs-4.col-md-6
                  .overlay-container.mb-10
                    = image_tag("gallery-3.jpg")
                    %a.overlay-link.small{:href => "portfolio-item.html"}
                      %i.fa.fa-link
                .col-xs-4.col-md-6
                  .overlay-container.mb-10
                    = image_tag("gallery-4.jpg")
                    %a.overlay-link.small{:href => "portfolio-item.html"}
                      %i.fa.fa-link
                .col-xs-4.col-md-6
                  .overlay-container.mb-10
                    = image_tag("gallery-5.jpg")
                    %a.overlay-link.small{:href => "portfolio-item.html"}
                      %i.fa.fa-link
                .col-xs-4.col-md-6
                  .overlay-container.mb-10
                    = image_tag("gallery-6.jpg")
                    %a.overlay-link.small{:href => "portfolio-item.html"}
                      %i.fa.fa-link
              .text-right.space-top
                %a.link-dark{:href => "portfolio-grid-2-3-col.html"}
                  %i.fa.fa-plus-circle.pl-5.pr-5>
                  More
          .col-md-3
            .footer-content
              %h2.title Kết nối cùng #{Shoppe.settings.store_name}
              .separator-2
              %p
                .fb-page{"data-adapt-container-width" => "true", "data-hide-cover" => "false", "data-href" => "https://www.facebook.com/lolemspaphanthiet/", "data-show-facepile" => "true", "data-small-header" => "false"}
                  .fb-xfbml-parse-ignore
                    %blockquote{:cite => "https://www.facebook.com/lolemspaphanthiet/"}
                      %a{:href => "https://www.facebook.com/lolemspaphanthiet/"} #{Shoppe.settings.store_name}
              .separator-2
              %ul.list-icons
                %li
                  %i.fa.fa-map-marker.pr-10.text-default
                  #{Shoppe.settings.store_address}
                %li
                  %i.fa.fa-phone.pr-10.text-default
                  #{Shoppe.settings.store_tel}
                %li
                  %a{:href => "mailto:info@vicdina.com"}
                    %i.fa.fa-envelope-o.pr-10>
                    #{Shoppe.settings.email_address}
  / .footer end
  / .subfooter start
  / ================
  .subfooter
    .container
      .subfooter-inner
        .row
          .col-md-12
            %p.text-center
              Copyright @ 2016 by
              = succeed "." do
                %a{:href => "http://lolemspa.com", :target => "_blank"} #{Shoppe.settings.store_name}
              All Rights Reserved
  / .subfooter end
  / footer end
  / page-wrapper end
  #fb-root
:javascript
  (function(d, s, id) {
    var js, fjs = d.getElementsByTagName(s)[0];
    if (d.getElementById(id)) return;
    js = d.createElement(s); js.id = id;
    js.src = "//connect.facebook.net/vi_VN/sdk.js#xfbml=1&version=v2.6&appId=378049169055908";
    fjs.parentNode.insertBefore(js, fjs);
  }(document, 'script', 'facebook-jssdk'));

app/views/shared/_header.html.haml
/ header-container start
.header-container
  / header-top start
  / classes:
  / "dark": dark version of header top e.g. class="header-top dark"
  / "colored": colored version of header top e.g. class="header-top colored"
  / ================
  .header-top.dark
    .container
      .row
        .col-xs-3.col-sm-6.col-md-9
          / header-top-first start
          / ================
          .header-top-first.clearfix
            %ul.social-links.circle.small.clearfix.hidden-xs
              %li.twitter
                %a{:href => "http://www.twitter.com", :target => "_blank"}
                  %i.fa.fa-twitter
              %li.skype
                %a{:href => "http://www.skype.com", :target => "_blank"}
                  %i.fa.fa-skype
              %li.linkedin
                %a{:href => "http://www.linkedin.com", :target => "_blank"}
                  %i.fa.fa-linkedin
              %li.googleplus
                %a{:href => "http://plus.google.com", :target => "_blank"}
                  %i.fa.fa-google-plus
              %li.youtube
                %a{:href => "http://www.youtube.com", :target => "_blank"}
                  %i.fa.fa-youtube-play
              %li.flickr
                %a{:href => "http://www.flickr.com", :target => "_blank"}
                  %i.fa.fa-flickr
              %li.facebook
                %a{:href => "http://www.facebook.com", :target => "_blank"}
                  %i.fa.fa-facebook
              %li.pinterest
                %a{:href => "http://www.pinterest.com", :target => "_blank"}
                  %i.fa.fa-pinterest
            .social-links.hidden-lg.hidden-md.hidden-sm.circle.small
              .btn-group.dropdown
                %button.btn.dropdown-toggle{"data-toggle" => "dropdown", :type => "button"}
                  %i.fa.fa-share-alt
                %ul.dropdown-menu.dropdown-animation
                  %li.twitter
                    %a{:href => "http://www.twitter.com", :target => "_blank"}
                      %i.fa.fa-twitter
                  %li.skype
                    %a{:href => "http://www.skype.com", :target => "_blank"}
                      %i.fa.fa-skype
                  %li.linkedin
                    %a{:href => "http://www.linkedin.com", :target => "_blank"}
                      %i.fa.fa-linkedin
                  %li.googleplus
                    %a{:href => "http://plus.google.com", :target => "_blank"}
                      %i.fa.fa-google-plus
                  %li.youtube
                    %a{:href => "http://www.youtube.com", :target => "_blank"}
                      %i.fa.fa-youtube-play
                  %li.flickr
                    %a{:href => "http://www.flickr.com", :target => "_blank"}
                      %i.fa.fa-flickr
                  %li.facebook
                    %a{:href => "http://www.facebook.com", :target => "_blank"}
                      %i.fa.fa-facebook
                  %li.pinterest
                    %a{:href => "http://www.pinterest.com", :target => "_blank"}
                      %i.fa.fa-pinterest
            %ul.list-inline.hidden-sm.hidden-xs
              %li
                %i.fa.fa-map-marker.pr-5.pl-10>
                #{Shoppe.settings.store_address}
              %li
                %i.fa.fa-phone.pr-5.pl-10>
                #{Shoppe.settings.store_tel}
              %li
                %i.fa.fa-envelope-o.pr-5.pl-10
                info@vicdina.com
        / header-top-first end
        .col-xs-9.col-sm-6.col-md-3
          / header-top-second start
          / ================
          #header-top-second.clearfix
            / header top dropdowns start
            / ================
            .header-top-dropdown.text-right
              .btn-group
                %a.btn.btn-default.btn-sm{:href => "#"}
                  %i.fa.fa-user.pr-10
                  Đăng ký
              .btn-group.dropdown
                %button.btn.dropdown-toggle.btn-default.btn-sm{"data-toggle" => "dropdown", :type => "button"}
                  %i.fa.fa-lock.pr-10
                  Đăng nhập
                %ul.dropdown-menu.dropdown-menu-right.dropdown-animation
                  %li
                    %form.login-form.margin-clear
                      .form-group.has-feedback
                        %label.control-label Username
                        %input.form-control{:placeholder => "", :type => "text"}
                          %i.fa.fa-user.form-control-feedback
                      .form-group.has-feedback
                        %label.control-label Password
                        %input.form-control{:placeholder => "", :type => "password"}
                          %i.fa.fa-lock.form-control-feedback
                      %button.btn.btn-gray.btn-sm{:type => "submit"} Log In
                      %span.pl-5.pr-5 or
                      %button.btn.btn-default.btn-sm{:type => "submit"} Sing Up
                      %ul
                        %li
                          %a{:href => "#"} Forgot your password?
                      %span.text-center Đăng nhập with
                      %ul.social-links.circle.small.colored.clearfix
                        %li.facebook
                          %a{:href => "http://www.facebook.com", :target => "_blank"}
                            %i.fa.fa-facebook
                        %li.twitter
                          %a{:href => "http://www.twitter.com", :target => "_blank"}
                            %i.fa.fa-twitter
                        %li.googleplus
                          %a{:href => "http://plus.google.com", :target => "_blank"}
                            %i.fa.fa-google-plus
  / header top dropdowns end
  / header-top-second end
  / header-top end
  / header start
  / classes:
  / "fixed": enables fixed navigation mode (sticky menu) e.g. class="header fixed clearfix"
  / "dark": dark version of header e.g. class="header dark clearfix"
  / "full-width": mandatory class for the full-width menu layout
  / "centered": mandatory class for the centered logo layout
  / ================
  %header.header.fixed.clearfix
    .container
      .row
        .col-md-3
          / header-left start
          / ================
          .header-left.clearfix
            / logo
            #logo.logo
              %a{:href => root_path}
                = image_tag('logo.png')
        / name-and-slogan
        /.site-slogan{:style => "letter-spacing: 3px;"}
        /  cosmetic,. ltd
        / header-left end
        .col-md-9
          / header-right start
          / ================
          .header-right.clearfix
            / main-navigation start
            / classes:
            / "onclick": Makes the dropdowns open on click, this the default bootstrap behavior e.g. class="main-navigation onclick"
            / "animated": Enables animations on dropdowns opening e.g. class="main-navigation animated"
            / "with-dropdown-buttons": Mandatory class that adds extra space, to the main navigation, for the search and cart dropdowns
            / ================
            .main-navigation.animated.with-dropdown-buttons
              / navbar start
              / ================
              %nav.navbar.navbar-default{:role => "navigation"}
                .container-fluid
                  / Toggle get grouped for better mobile display
                  .navbar-header
                    %button.navbar-toggle{"data-target" => "#navbar-collapse-1", "data-toggle" => "collapse", :type => "button"}
                      %span.sr-only Toggle navigation
                      %span.icon-bar
                      %span.icon-bar
                      %span.icon-bar
                  / Collect the nav links, forms, and other content for toggling
                  #navbar-collapse-1.collapse.navbar-collapse
                    / main-menu
                    %ul.nav.navbar-nav
                      %li=link_to 'Trang chủ',:root
                      %li=link_to(t("shoppe.services.services"),:services)
                      %li=link_to t('Shoppe.menu.blogs') ,posts_path
                    / main-menu end
                    / header dropdown buttons
                    .header-dropdown-buttons.hidden-xs
                      .btn-group.dropdown
                        %button.btn.dropdown-toggle{"data-toggle" => "dropdown", :type => "button"}
                          %i.icon-search
                        %ul.dropdown-menu.dropdown-menu-right.dropdown-animation
                          %li
                            %form.search-box.margin-clear{:role => "search"}
                              .form-group.has-feedback
                                %input.form-control{:placeholder => "Search", :type => "text"}
                                  %i.icon-search.form-control-feedback
                      .btn-group.dropdown
                        %button.btn.dropdown-toggle{"data-toggle" => "dropdown", :type => "button"}
                          %i.icon-basket-1
                          %span.cart-count.default-bg= current_order.total_items
                        %ul.dropdown-menu.dropdown-menu-right.dropdown-animation.cart
                          %li
                            %table.table.table-hover
                              %thead
                                %tr
                                  %th.quantity QTY
                                  %th.product Sản phẩm
                                  %th.amount Tổng
                              %tbody
                                %tr
                                  %td.quantity 2 x
                                  %td.product
                                    %a{:href => "shop-product.html"} Android 4.4 Smartphone
                                    %span.small 4.7" Dual Core 1GB
                                  %td.amount $199.00
                            .panel-body.text-right
                              %a.btn.btn-group.btn-gray.btn-sm{:href => "shop-cart.html"} View Cart
                              %a.btn.btn-group.btn-gray.btn-sm{:href => "shop-checkout.html"} Checkout
  / header dropdown buttons end
  / navbar end
  / main-navigation end
  / header-right end
  / header end
  / header-container end

app/views/shared/_members.html.haml
.owl-carousel.content-slider
  .container
    .row
      .col-md-8.col-md-offset-2
        .testimonial.text-center
          .testimonial-image
            = image_tag("members/thuy_tram.jpg")
          %h3 Tuyệt vời!
          .separator
          .testimonial-body
            %blockquote
              %p
                Hôm nay mình có dịp ghé Lọ Lem Spa Phan Thiết,mình mới vừa hấp trắng tiêm căng bóng da, thây hiệu quả rất là tốt,da mình mới hấp có một lần thôi mà lên tone quá trời luôn, lúc trước da mặt mình thâm quá trời luôn nhưng mà điều trị có một lẩn thôi mà đã cải thiện rất là tốt
                những vết thâm thì mờ bớt đi, da mặt thì thấy căng hơn và sáng hơn nữa, mình không cần thoa kem mà thấy da mình vẫn sáng. mình rất là cảm ơn Lọ Lem Spa.
            .testimonial-info-1 - Triệu Yến Trân
            .testimonial-info-2 Lương Sơn - Bắc Bình - Bình Thuận
  .container
    .row
      .col-md-8.col-md-offset-2
        .testimonial.text-center
          .testimonial-image
            = image_tag("testimonial-2.jpg")
          %h3 Amazing!
          .separator
          .testimonial-body
            %blockquote
              %p
                Lorem ipsum dolor sit amet, consectetur adipisicing elit. Et cupiditate deleniti ratione in.
                Expedita nemo, quisquam, fuga adipisci omnis ad mollitia libero culpa nostrum est quia eos esse
                vel!
            .testimonial-info-1 - Jane Doe
            .testimonial-info-2 By Company

app/views/shared/_reasons.html.haml
%ul.reasons
  %li.support
    %h4 Free technical support
    %p We'll help you get your phone working. Just call or e-mail us.
  %li.quality
    %h4 Quality assurance
    %p We check all the produts we ship so you can rely on us.
  %li.delivery
    %h4 Next day delivery
    %p Order before 4pm and your order will be with you the next business day.

app/views/shared/_recent_post.html.haml
-@posts = Post.all.order(updated_at: :desc).limit(5)
%h2.title Bài viết mới
.separator-2
-if !@posts.empty?
  -for post in @posts
    .media.margin-clear
      .media-left
        .overlay-container
          =image_tag(post.default_image ? post.default_image.path : '',:class=>'media-object')
          %a.overlay-link.small{:href => post.permalink}
            %i.fa.fa-link
      .media-body
        %h6.media-heading
          = link_to truncate(post.title,length: 60), post_path(post.post_category.permalink,post.permalink)
        %p.small.margin-clear
          %i.fa.fa-calendar.pr-10>
          #{post.updated_at.strftime("%H:%M %d - %m - %Y")}
      %hr
  .text-right.space-top
    %a.link-dark{:href => "blog-large-image-right-sidebar.html"}
      %i.fa.fa-plus-circle.pl-5.pr-5>
      Xem thêm

app/views/shared/_service_list.html.haml
%section.light-gray-bg.pv-30.clearfix
  .container
    .row
      .col-md-8.col-md-offset-2
        %h2.text-center
          Dịch vụ của
          %strong Lọ Lem Spa
        .separator
        %p.large.text-center Ai bảo gái Phan Thiết không trắng???
        %p=image_tag("logo.png",:class => "center-block")
        %p Với công nghệ hấp trắng Hàn Quốc độc quyền tại Lọ Lem Spa mang đến cho các bạn gái Phan Thiết làn da trắng nổi bật, trắng rạng rỡ ko trắng ko lấy tiền .Cam kết trắng hoàn hảo 100%. Làn da trắng không còn là trở ngại khó khăn nữa đâu nhé. Công nghệ độc quyền, máy móc hiện đại mang đến cho các bạn vẻ ngoài thay đổi vượt trội.
        - if !services.empty?
          - for service in services
            .col-sm-6
              .image-box.style-2.mb-20.bordered.dark-bg
                .overlay-container.overlay-visible
                  %img{:alt => "", :src => service.default_image ? service.default_image.path : ''}
                  =link_to service_path(service.permalink), class: 'overlay-link' do
                    %i.fa.fa-link
                .body
                  %h3= service.name
                  .separator-2
                  %p.text-muted=service.excerpt
                  %a.btn.btn-gray-transparent.btn-animated.btn-sm.margin-clear{:href => "#"}
                    Xem
                    %i.fa.fa-arrow-right.pl-10